### ISSUE TITLE
Unclear where images/video are saved

### ISSUE THREAD

**Issue by weex** [NeonGeckoCom/skill-camera#33]
Found this skill in /home/neon/venv/lib/python3.7/site-packages with `ls -1 | grep neon_skill` and the Mark II took a picture and a video but I can't easily find them on the filesystem.

**Comment by NeonDaniel** [comment]
Those should be in `~/Picutres` and `~/Videos`, respectively. https://github.com/NeonGeckoCom/skill-camera/blob/master/__init__.py#L55

There's an open issue for displaying those on request (#29) which will likely make that path configurable as well (but keep the current default)

**Comment by weex** [comment]
Thanks. Found images in ~/Pictures/Neon which I'd tabbed right past to ~/Pictures/Neon/local. I'll PR the Readme to add this as a note.

Per the chat, I understand the Video intent doesn't work at this time.
